# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\S.O.F.T.S\PIRENEA\PYTHON\asan\src\gui\parameters_qt.ui'
#
# Created by: PyQt5 UI code generator 5.5
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_DockWidget_Parameters(object):
    def setupUi(self, DockWidget_Parameters):
        DockWidget_Parameters.setObjectName("DockWidget_Parameters")
        DockWidget_Parameters.resize(310, 320)
        DockWidget_Parameters.setMinimumSize(QtCore.QSize(310, 320))
        DockWidget_Parameters.setMaximumSize(QtCore.QSize(310, 350))
        DockWidget_Parameters.setFeatures(QtWidgets.QDockWidget.DockWidgetFloatable|QtWidgets.QDockWidget.DockWidgetMovable)
        DockWidget_Parameters.setAllowedAreas(QtCore.Qt.LeftDockWidgetArea|QtCore.Qt.RightDockWidgetArea)
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.lineEdit_File = QtWidgets.QLineEdit(self.dockWidgetContents)
        self.lineEdit_File.setEnabled(False)
        self.lineEdit_File.setGeometry(QtCore.QRect(10, 120, 81, 20))
        self.lineEdit_File.setMaxLength(32763)
        self.lineEdit_File.setObjectName("lineEdit_File")
        self.plainTextEdit_Header = QtWidgets.QPlainTextEdit(self.dockWidgetContents)
        self.plainTextEdit_Header.setGeometry(QtCore.QRect(10, 140, 280, 150))
        self.plainTextEdit_Header.setMaximumSize(QtCore.QSize(16777215, 150))
        self.plainTextEdit_Header.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.plainTextEdit_Header.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.plainTextEdit_Header.setObjectName("plainTextEdit_Header")
        self.groupBox_Calibration = QtWidgets.QGroupBox(self.dockWidgetContents)
        self.groupBox_Calibration.setEnabled(False)
        self.groupBox_Calibration.setGeometry(QtCore.QRect(10, 10, 181, 91))
        self.groupBox_Calibration.setObjectName("groupBox_Calibration")
        self.doubleSpinBox_Tof1 = QtWidgets.QDoubleSpinBox(self.groupBox_Calibration)
        self.doubleSpinBox_Tof1.setGeometry(QtCore.QRect(10, 20, 80, 20))
        self.doubleSpinBox_Tof1.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.doubleSpinBox_Tof1.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.doubleSpinBox_Tof1.setDecimals(1)
        self.doubleSpinBox_Tof1.setMaximum(100000.0)
        self.doubleSpinBox_Tof1.setProperty("value", 30409.0)
        self.doubleSpinBox_Tof1.setObjectName("doubleSpinBox_Tof1")
        self.doubleSpinBox_Mass1 = QtWidgets.QDoubleSpinBox(self.groupBox_Calibration)
        self.doubleSpinBox_Mass1.setGeometry(QtCore.QRect(90, 20, 80, 20))
        self.doubleSpinBox_Mass1.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.doubleSpinBox_Mass1.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.doubleSpinBox_Mass1.setDecimals(4)
        self.doubleSpinBox_Mass1.setMaximum(2000.0)
        self.doubleSpinBox_Mass1.setProperty("value", 215.0099)
        self.doubleSpinBox_Mass1.setObjectName("doubleSpinBox_Mass1")
        self.doubleSpinBox_Mass2 = QtWidgets.QDoubleSpinBox(self.groupBox_Calibration)
        self.doubleSpinBox_Mass2.setGeometry(QtCore.QRect(90, 40, 80, 20))
        self.doubleSpinBox_Mass2.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.doubleSpinBox_Mass2.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.doubleSpinBox_Mass2.setDecimals(4)
        self.doubleSpinBox_Mass2.setMaximum(2000.0)
        self.doubleSpinBox_Mass2.setProperty("value", 298.0274)
        self.doubleSpinBox_Mass2.setObjectName("doubleSpinBox_Mass2")
        self.doubleSpinBox_Tof2 = QtWidgets.QDoubleSpinBox(self.groupBox_Calibration)
        self.doubleSpinBox_Tof2.setGeometry(QtCore.QRect(10, 40, 80, 20))
        self.doubleSpinBox_Tof2.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.doubleSpinBox_Tof2.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.doubleSpinBox_Tof2.setDecimals(1)
        self.doubleSpinBox_Tof2.setMaximum(100000.0)
        self.doubleSpinBox_Tof2.setProperty("value", 35859.0)
        self.doubleSpinBox_Tof2.setObjectName("doubleSpinBox_Tof2")
        self.doubleSpinBox_Mass3 = QtWidgets.QDoubleSpinBox(self.groupBox_Calibration)
        self.doubleSpinBox_Mass3.setGeometry(QtCore.QRect(90, 60, 80, 20))
        self.doubleSpinBox_Mass3.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.doubleSpinBox_Mass3.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.doubleSpinBox_Mass3.setDecimals(4)
        self.doubleSpinBox_Mass3.setMaximum(2000.0)
        self.doubleSpinBox_Mass3.setProperty("value", 300.0228)
        self.doubleSpinBox_Mass3.setObjectName("doubleSpinBox_Mass3")
        self.doubleSpinBox_Tof3 = QtWidgets.QDoubleSpinBox(self.groupBox_Calibration)
        self.doubleSpinBox_Tof3.setGeometry(QtCore.QRect(10, 60, 80, 20))
        self.doubleSpinBox_Tof3.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.doubleSpinBox_Tof3.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.doubleSpinBox_Tof3.setDecimals(1)
        self.doubleSpinBox_Tof3.setMaximum(100000.0)
        self.doubleSpinBox_Tof3.setProperty("value", 35980.0)
        self.doubleSpinBox_Tof3.setObjectName("doubleSpinBox_Tof3")
        self.pushButton_ApplyCalib = QtWidgets.QPushButton(self.dockWidgetContents)
        self.pushButton_ApplyCalib.setEnabled(False)
        self.pushButton_ApplyCalib.setGeometry(QtCore.QRect(200, 45, 100, 25))
        self.pushButton_ApplyCalib.setCheckable(False)
        self.pushButton_ApplyCalib.setObjectName("pushButton_ApplyCalib")
        self.pushButton_ChangeCalib = QtWidgets.QPushButton(self.dockWidgetContents)
        self.pushButton_ChangeCalib.setEnabled(False)
        self.pushButton_ChangeCalib.setGeometry(QtCore.QRect(200, 20, 100, 25))
        self.pushButton_ChangeCalib.setCheckable(False)
        self.pushButton_ChangeCalib.setObjectName("pushButton_ChangeCalib")
        self.pushButton_SaveCalibData = QtWidgets.QPushButton(self.dockWidgetContents)
        self.pushButton_SaveCalibData.setEnabled(False)
        self.pushButton_SaveCalibData.setGeometry(QtCore.QRect(200, 70, 100, 25))
        self.pushButton_SaveCalibData.setCheckable(False)
        self.pushButton_SaveCalibData.setObjectName("pushButton_SaveCalibData")
        self.pushButton_SaveMmassData = QtWidgets.QPushButton(self.dockWidgetContents)
        self.pushButton_SaveMmassData.setEnabled(False)
        self.pushButton_SaveMmassData.setGeometry(QtCore.QRect(170, 110, 130, 25))
        self.pushButton_SaveMmassData.setCheckable(False)
        self.pushButton_SaveMmassData.setObjectName("pushButton_SaveMmassData")
        DockWidget_Parameters.setWidget(self.dockWidgetContents)

        self.retranslateUi(DockWidget_Parameters)
        QtCore.QMetaObject.connectSlotsByName(DockWidget_Parameters)

    def retranslateUi(self, DockWidget_Parameters):
        _translate = QtCore.QCoreApplication.translate
        DockWidget_Parameters.setWindowTitle(_translate("DockWidget_Parameters", "Parameters"))
        self.groupBox_Calibration.setTitle(_translate("DockWidget_Parameters", "Calibration"))
        self.pushButton_ApplyCalib.setText(_translate("DockWidget_Parameters", "Apply Calibration"))
        self.pushButton_ChangeCalib.setText(_translate("DockWidget_Parameters", "Change Calibration"))
        self.pushButton_SaveCalibData.setText(_translate("DockWidget_Parameters", "Save Calib. Data"))
        self.pushButton_SaveMmassData.setText(_translate("DockWidget_Parameters", "Save to Mmass Format"))

